Various updates, fixes and additions
mage-os/php-dependency-list pull request #1
Opened 2023-01-31 11:57 UTC by adamzero1

- feat: box-project version updated
- fixed: unable to build project phar
- feat: added the ability to specify multiple code parse types, php/di.xml/composer.json/module.xml 
  These can be specified as desired, all `--all` can be used
- feat: help text, now shows a version (just for ease in future should there be more updates)
- docs: updated docs with descriptions/commands on how to build and test
- feat: added dockerfile, so builds can be done in a common environment
- refactor: have refactored some of the clases into common directories, such as `code parsers` and `code providers`
- feat: have added the option to allow for a json output (so the output can be easily parsed by other scripts)
- feat: have added the option to "enable module name" to add the referenced classes module name in the output
- feat: have added the option to "enable source file" to add the referenced classes source file path in the output
- feat: code providers can now be passed a list of valid patterns, this has two bonuses: 
  - they can return multiple file types
  - they only return file types we want
- feat: added some utility scripts to the bin directory, for ease of dev / testing / building
- fixed: issue where references would sometimes be returned as a standard array and sometimes as an assoc array, this is now always a standard array
- feat: added code parser type `composer.json`
- feat: added code parser type `module.xml`

  
All changes should be backwards compatible.

2023-02-12 16:43 UTC, Vinai requested changes
This is great! The only thing that bugs me a little bit is some of the formatting.
So for example, for [functions](https://www.php-fig.org/psr/psr-12/#44-methods-and-functions), instead of `printHelpEndExit(){` I am used to the PSR-2 - or,12 nowadays, I guess - style
```php
printHelpEndExit()
{
```

And for [conditionals](https://www.php-fig.org/psr/psr-12/#51-if-elseif-else) like `if(count($argv) > 1){` a space between the parens and braces and such

```php
if (count($argv) > 1) {
```

I tried to be bigger and let it go but I couldn't ;)
Happy to apply the changes myself after merging if you don't like it.

2023-02-26 14:06 UTC, adamzero1 commented
No worries, I've added gitbub workflow file to the project that should check for PSR12.
Though it doesn't seem to be running, not sure if this is because it's a fork and I don't have permissions or something.

Let me know if you need / want anything else

2023-02-27 08:26 UTC, Vinai approved these changes
LGTM

2024-12-17 20:56 UTC, fballiano approved these changes
since @Vinai is the original author and approved this PR, I'm approving to allow merging

2024-12-17 20:57 UTC, fballiano commented
@adamzero1 @Vinai @sprankhub @rhoerr do you know who has write privileges to this repo? we can't merge this PR.

2024-12-17 21:01 UTC, fballiano approved these changes
minor "empty line at end of files" suggestion

2024-12-17 21:01 UTC, fballiano commented on bin/build-docker-image
> +docker build --build-arg UUID=$(id -u) --build-arg GUID=$(id -g) ./build --tag php-dependency-list-env:1.0.0
```suggestion
docker build --build-arg UUID=$(id -u) --build-arg GUID=$(id -g) ./build --tag php-dependency-list-env:1.0.0

```

2024-12-17 21:01 UTC, fballiano commented on bin/build-phar
> +docker run -t --volume $(pwd):/usr/src ${DOCKER_IMAGE} bash -c "make; exit $?"
```suggestion
docker run -t --volume $(pwd):/usr/src ${DOCKER_IMAGE} bash -c "make; exit $?"

```

2024-12-17 21:01 UTC, fballiano commented on box.json.dist
>  }
```suggestion
}

```

2024-12-17 21:01 UTC, fballiano commented on build/Dockerfile
> +USER mage
```suggestion
USER mage

```

2024-12-18 08:22 UTC, sprankhub commented
> @adamzero1 @Vinai @sprankhub @rhoerr do you know who has write privileges to this repo? we can't merge this PR.

Definitely `mage-os-ci`. Besides that, no idea from the top of my head. It seems to not be included in https://github.com/mage-os/terraform/blob/main/variables.tf, which is probably an oversight. I added it to https://github.com/mage-os/terraform/issues/14 now.

2024-12-18 08:46 UTC, fballiano commented
@mage-os-ci @mage-os/infrastructure could somebody take a look at this?

2024-12-18 21:04 UTC, merged